### PR TITLE
Minor Strict Concurrency fix

### PR DESCRIPTION
**Pull request by Supereg**
# Minor Strict Concurrency fix

## :recycle: Current situation & Problem
This PR adds a missing Sendable conformance.

## :gear: Release Notes 
* Add missing Sendable conformance.
* Allow arbitrary Regex Output types with ValidationRules (e.g., allows to pass Regex instances built with RegexBuilder).
* Don't require a `ValidationEngine` in the environment with `VerifiableTextField` for greater flexibility.

## :books: Documentation
--

## :white_check_mark: Testing
--

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by PSchmiedmayer — APPROVED** [review]
Thank you for looking into this!

Seems like we also need to update the Snapshot tests & other functionality to reflect the concurrency change to make the PR mergable

**Comment by Supereg** [comment]
@PSchmiedmayer the Snapshots test are failing within the CI. If you look at the xcresult bundle, the snapshot images don't differ though. I couldn't reproduce the failure locally. I also tried to regenerate the images (they resulted in the exact same binary representation).

**Comment by PSchmiedmayer** [comment]
@Supereg As noted on Slack: I unfortunately don't have a clear idea where this might come from, let me know if you want me to dig deeper into this!

**Comment by Supereg** [comment]
> @Supereg As noted on Slack: I unfortunately don't have a clear idea where this might come from, let me know if you want me to dig deeper into this!

Maybe we can wait for Xcode 16 beta 4 release today and see if that changes anything? Otherwise, let's discuss other strategies in the meeting later.

**Comment by PSchmiedmayer** [comment]
@Supereg I have just installed the Xcode 16 Beta 4 on all macOS runners that we host.

**Comment by Supereg** [comment]
> @Supereg I have just installed the Xcode 16 Beta 4 on all macOS runners that we host.

Just resolved the issue. It seems there is a difference, if the snapshot tests are run on the iOS 18 simulator vs on an iOS 17.5 simulator. The iOS 18 simulator slightly changes shadows around text which made all of the snapshot testing fail. This is now resolved.

I added some additional minor changes to the PR, like improving Sendable annotation of `ValidationRule`, allow arbitrarily built Regex instances with ValidationRule and slightly improving flexibility of the `VerifiableTextField`. I re-requested a review to cover those changes 👍

**Review by PSchmiedmayer — APPROVED** [review]
Thank you; those look good to me! 🚀

**Pull request merged**
